import { constants } from '@/constants';
import { getContextValues } from '@/helpers/getContextValues';
import { getValidListItem } from '@/helpers/getValidListItem';

import type { ConfigContext, I18nTextRecord, SortOrderingItem } from 'sanity';
import type { ChildResolverOptions, MenuItem, MenuItemGroup } from 'sanity/structure';

import type { GetListItemOriginalType, StructureToolParams } from '@/structure/types/common.types';
import type { ListItemCore } from '@/structure/types/listItem.types';
import type { ListItemChildren, ListItemTitle } from '@/structure/types/listItemDefinitions.types';
import type { SimpleMerge } from '@/types/lib.types';

/**
 * Context callback parameters containing options for resolving children and default menu items/groups.
 */
interface ListItemCallbackParams {
  /**
   * Options provided by the Sanity Studio children resolver context.
   */
  childOptions: ChildResolverOptions;
  /**
   * The default menu item groups generated by Sanity Studio.
   */
  prevMenuItemGroups: MenuItemGroup[];
  /**
   * The default menu items generated by Sanity Studio.
   */
  prevMenuItems: MenuItem[];
  /**
   * List of default pane view IDs.
   */
  defaultPaneViews: string[];
  /**
   * The display title string mapped to the translation key.
   */
  i18nTitle: string;
}

/**
 * Parameters configured on the getComputedListItems helper function.
 *
 * @template T - The structure tool configuration parameters schema.
 */
interface GetComputedListItemsParams<T extends StructureToolParams> {
  /**
   * The list item definition containing core options and children.
   */
  listItem: SimpleMerge<[Omit<ListItemCore<T>, 'id'>, ListItemChildren<T>]>;
  /**
   * The active Sanity config context.
   */
  context: ConfigContext;
}

/**
 * Function type that resolves all conditional/dynamic callbacks on a list item.
 * Evaluates fields lazily into their resolved static values or resolver functions.
 *
 * @template T - The structure tool configuration parameters schema.
 * @param params - The input list item definition and active Sanity config context.
 * @returns An object containing lazy resolver functions for each list item field.
 */
export type GetComputedListItems = <T extends StructureToolParams>(
  params: GetComputedListItemsParams<T>,
) => SimpleMerge<
  [
    {
      /**
       * Static configuration references or components evaluated directly.
       */
      [
        K in Extract<keyof GetComputedListItemsParams<T>['listItem'], 'component' | 'icon' | 'raw'>
      ]: ListItemCore<T>[K];
    },
    {
      /**
       * Basic list item parameters resolved at root level without extra context options.
       */
      [
        K in Extract<
          keyof GetComputedListItemsParams<T>['listItem'],
          'isDivider' | 'isPlural' | 'singleton'
        >
      ]: () => GetListItemOriginalType<ListItemCore<T>[K]>;
    },
    {
      /**
       * Custom/dynamic options resolved recursively down the structure path using active childOptions context.
       */
      [
        K in Extract<
          keyof GetComputedListItemsParams<T>['listItem'],
          | 'apiVersion'
          | 'componentOptions'
          | 'defaultLayout'
          | 'filter'
          | 'filterParams'
          | 'hideAddButton'
          | 'showIcons'
          | 'templates'
          | 'views'
        >
      ]: (
        params: Pick<ListItemCallbackParams, 'childOptions'>,
      ) => GetListItemOriginalType<ListItemCore<T>[K]>;
    },
    {
      /**
       * Resolves the child pane display title, dynamically receiving childOptions.
       */
      childTitle: (
        params: Pick<ListItemCallbackParams, 'childOptions'>,
      ) => NonNullable<GetListItemOriginalType<ListItemTitle<T>['child']>>;
      /**
       * Resolves nested child structural items, dynamically receiving childOptions.
       */
      children: (
        params: Pick<ListItemCallbackParams, 'childOptions'>,
      ) => NonNullable<GetListItemOriginalType<ListItemChildren<T>['children']>>;
      /**
       * Resolves and maps sort ordering items, dynamically receiving childOptions.
       */
      defaultOrdering: (
        params: Pick<ListItemCallbackParams, 'childOptions'>,
      ) => SortOrderingItem[] | undefined;
      /**
       * Resolves default pane view configurations, dynamically receiving childOptions and views list.
       */
      defaultPanes: (
        params: Pick<ListItemCallbackParams, 'childOptions' | 'defaultPaneViews'>,
      ) => GetListItemOriginalType<ListItemCore<T>['defaultPanes']>;
      /**
       * Resolves the internationalized text record for this item's display titles.
       */
      i18n: (params: Pick<ListItemCallbackParams, 'i18nTitle'>) => I18nTextRecord<'title'>;
      /**
       * Statically resolves whether this list item is visible in the pane menu hierarchy.
       */
      isVisible: () => NonNullable<GetListItemOriginalType<ListItemCore<T>['isVisible']>>;
      /**
       * Resolves custom grouped menu actions, dynamically receiving childOptions and baseline prev groups.
       */
      menuItemGroups: (
        params: Pick<ListItemCallbackParams, 'childOptions' | 'prevMenuItemGroups'>,
      ) => GetListItemOriginalType<ListItemCore<T>['menuItemGroups']>;
      /**
       * Resolves custom header menu items, dynamically receiving childOptions and baseline prev items.
       */
      menuItems: (
        params: Pick<ListItemCallbackParams, 'childOptions' | 'prevMenuItems'>,
      ) => GetListItemOriginalType<ListItemCore<T>['menuItems']>;
      /**
       * Statically resolves the display title seen in the parent pane.
       */
      parentTitle: () => NonNullable<GetListItemOriginalType<ListItemTitle<T>['parent']>>;
      /**
       * Statically resolves the document schema type name.
       */
      schemaType: () => NonNullable<GetListItemOriginalType<ListItemCore<T>['schemaType']>>;
    },
  ]
>;

/**
 * Evaluates all dynamic/conditional callbacks on a list item and exposes them as lazy resolver functions.
 *
 * @template T - The structure tool configuration parameters schema.
 * @param params - The input list item definition and active Sanity config context.
 * @returns An object containing lazy resolver functions for each list item field.
 */
export const getComputedListItems: GetComputedListItems = ({ listItem, context }) => {
  const contextValues = getContextValues(context);

  const {
    apiVersion,
    children,
    component,
    componentOptions,
    defaultLayout,
    defaultOrdering,
    defaultPanes,
    filter,
    filterParams,
    hideAddButton,
    i18n,
    icon,
    isDivider,
    isPlural,
    isVisible,
    menuItemGroups,
    menuItems,
    raw,
    schemaType,
    showIcons,
    singleton,
    templates,
    title,
    views,
  } = listItem;

  const displayTitle = getValidListItem(title, contextValues);

  return {
    /**
     * Resolves the Sanity API version used for queries.
     */
    apiVersion: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(apiVersion, { ...contextValues, ...params }),
    /**
     * Resolves the list item display title as seen in the child pane.
     */
    childTitle: (params: Pick<ListItemCallbackParams, 'childOptions'>) => {
      if (typeof displayTitle === 'object') {
        const { child } = displayTitle;

        return getValidListItem(child, { ...contextValues, ...params }) ?? '';
      }

      return displayTitle ?? '';
    },
    /**
     * Resolves nested child list item definitions.
     */
    children: (params) => getValidListItem(children, { ...contextValues, ...params }) ?? [],
    /**
     * The custom React user component rendering this pane.
     */
    component,
    /**
     * Resolves custom configuration options passed to the component.
     */
    componentOptions: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(componentOptions, { ...contextValues, ...params }),
    /**
     * Resolves the default listed preview layout style.
     */
    defaultLayout: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(defaultLayout, { ...contextValues, ...params }),
    /**
     * Resolves and parses default document sorting rules.
     */
    defaultOrdering: (params: Pick<ListItemCallbackParams, 'childOptions'>) => {
      const defaultOrderingValue = getValidListItem(defaultOrdering, {
        ...contextValues,
        ...params,
      });

      if (defaultOrderingValue) {
        return Object.entries(defaultOrderingValue).map(([field, value]) => ({
          field,
          ...(typeof value === 'string' ? { direction: value } : value),
        }));
      }

      return defaultOrderingValue;
    },
    /**
     * Resolves the list of default active view tab IDs for this document editor pane.
     */
    defaultPanes: (params: Pick<ListItemCallbackParams, 'childOptions' | 'defaultPaneViews'>) => {
      const { childOptions, defaultPaneViews } = params;

      return getValidListItem(defaultPanes, {
        ...contextValues,
        childOptions,
        views: defaultPaneViews,
      });
    },
    /**
     * Resolves the GROQ query string filter.
     */
    filter: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(filter, { ...contextValues, ...params }),
    /**
     * Resolves the parameters for the GROQ filter query.
     */
    filterParams: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(filterParams, { ...contextValues, ...params }),
    /**
     * Resolves whether the document creation add button is hidden.
     */
    hideAddButton: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(hideAddButton, { ...contextValues, ...params }),
    /**
     * Resolves translation configurations mapping the list item titles to translation bundles.
     */
    i18n: (params: Pick<ListItemCallbackParams, 'i18nTitle'>) => {
      const value = getValidListItem(i18n, contextValues);

      if (value) {
        return {
          title: {
            key: params.i18nTitle,
            ns: constants.I18N_NAMESPACE,
          },
        };
      }

      return {};
    },
    /**
     * The visual icon component/reference.
     */
    icon,
    /**
     * Resolves whether the item is rendered as a visual list divider.
     */
    isDivider: () => getValidListItem(isDivider, contextValues),
    /**
     * Resolves whether the schema type name title should be pluralized.
     */
    isPlural: () => getValidListItem(isPlural, contextValues),
    /**
     * Resolves whether the list item is visible in the pane menu structure.
     */
    isVisible: () => getValidListItem(isVisible, contextValues) ?? true,
    /**
     * Resolves collapsed group actions in the pane header menu.
     */
    menuItemGroups: (
      params: Pick<ListItemCallbackParams, 'childOptions' | 'prevMenuItemGroups'>,
    ) => {
      const { childOptions, prevMenuItemGroups } = params;

      return getValidListItem(menuItemGroups, {
        ...contextValues,
        childOptions,
        prev: prevMenuItemGroups,
      });
    },
    /**
     * Resolves action items shown in the pane header menu.
     */
    menuItems: (params: Pick<ListItemCallbackParams, 'childOptions' | 'prevMenuItems'>) => {
      const { childOptions, prevMenuItems } = params;

      return getValidListItem(menuItems, {
        ...contextValues,
        childOptions,
        prev: prevMenuItems,
      });
    },
    /**
     * Resolves the list item display title as seen in the parent pane.
     */
    parentTitle: () => {
      if (typeof displayTitle === 'object') {
        const { parent } = displayTitle;

        return getValidListItem(parent, contextValues) ?? '';
      }

      return displayTitle ?? '';
    },
    /**
     * The imperative layout escape hatch callback.
     */
    raw,
    /**
     * Resolves the schema document type name.
     */
    schemaType: () => getValidListItem(schemaType, contextValues) ?? '',
    /**
     * Controls whether child document icons are displayed in the list view.
     */
    showIcons: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(showIcons, { ...contextValues, ...params }),
    /**
     * Resolves whether this item is treated as a singleton.
     */
    singleton: () => getValidListItem(singleton, contextValues),
    /**
     * Resolves initial value template overrides.
     */
    templates: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(templates, { ...contextValues, ...params }),
    /**
     * Resolves custom pane view tabs (e.g. form, preview, components) configured for this document editor.
     */
    views: (params: Pick<ListItemCallbackParams, 'childOptions'>) =>
      getValidListItem(views, { ...contextValues, ...params }),
  };
};
