import type { Plugin, TemplateResolver } from 'sanity';
import type { RequireAllOrNone } from 'type-fest';

import type { DefineListItem } from '@/factories/defineListItem';
import type { DefineListItems } from '@/factories/defineListItems';
import type { Helpers } from '@/factories/helpers';
import type {
  StructureToolGenericParam,
  StructureToolParams,
} from '@/structure/types/common.types';
import type { ListItem } from '@/structure/types/listItem.types';
import type { SimpleMerge } from '@/types/lib.types';

/**
 * Core configuration parameters for the structure tool.
 *
 * @template T - The structure tool configuration parameters schema.
 */
export interface StructureToolCoreParams<T extends StructureToolParams> {
  /**
   * The display title of the structure tool's root list. Can be a static string or a dynamic function.
   */
  title: StructureToolGenericParam<T, string>;
  /**
   * Optional title shown when a list is empty. Can be a static string or a dynamic function.
   */
  emptyListTitle?: StructureToolGenericParam<T, string>;
  /**
   * If true (default), automatically registers initial value templates for singleton/listing documents.
   */
  enableAutoGenerateTemplates?: boolean;
}

/**
 * Parameters for defining workspace restrictions on the structure tool.
 *
 * @template T - The structure tool configuration parameters schema, containing Workspaces and DefaultWorkspaces.
 */
export interface StructureToolWorkspaceParams<
  T extends Pick<StructureToolParams, 'Workspaces' | 'DefaultWorkspaces'>,
> {
  /**
   * Restricts visibility of the structure tool to specific workspaces.
   */
  workspaces?: T['Workspaces'];
  /**
   * Workspace names that will be selected by default.
   */
  defaultWorkspaces?: T['DefaultWorkspaces'];
}

/**
 * Parameters for defining role restrictions on the structure tool.
 *
 * @template T - The structure tool configuration parameters schema, containing Roles and DefaultRoles.
 */
export interface StructureToolRoleParams<
  T extends Pick<StructureToolParams, 'Roles' | 'DefaultRoles'>,
> {
  /**
   * Restricts visibility of the structure tool to users with specific roles.
   */
  roles?: T['Roles'];
  /**
   * Role names that will be selected by default.
   */
  defaultRoles?: T['DefaultRoles'];
}

/**
 * Plugin parameters merging workspace and role restriction configurations.
 *
 * @template T - The structure tool configuration parameters schema.
 */
export type PluginParams<T extends StructureToolParams> = SimpleMerge<
  [StructureToolWorkspaceParams<T>, StructureToolRoleParams<T>]
>;

/**
 * Complete set of input configuration parameters for the structure tool plugin.
 * Combines core parameters with workspace and role parameters (which must be configured entirely or not at all).
 *
 * @template T - The structure tool configuration parameters schema.
 */
export type StructureToolPluginParams<T extends StructureToolParams> = SimpleMerge<
  [
    StructureToolCoreParams<T>,
    RequireAllOrNone<StructureToolWorkspaceParams<T>>,
    RequireAllOrNone<StructureToolRoleParams<T>>,
  ]
>;

/**
 * Parameters passed to internal components generated by the structure tool plugin.
 *
 * @template T - The structure tool configuration parameters schema.
 */
interface StructureToolPluginOutputParams<T extends StructureToolParams> {
  /**
   * The list items defining the content structure hierarchy.
   */
  listItems: ListItem<T>[];
}

/**
 * The output returned by creating a structure tool plugin.
 * Extends the workspace configuration with structure definitions and helper utilities.
 *
 * @template T - The structure tool configuration parameters schema.
 */
export interface StructureToolPluginOutput<T extends StructureToolParams> {
  /**
   * The generated Sanity Studio plugin representing the content structure hierarchy.
   */
  structure: Plugin<StructureToolPluginOutputParams<T>>;
  /**
   * A function that generates the template resolver for initial value templates.
   */
  templates: (params: StructureToolPluginOutputParams<T>) => TemplateResolver;
  /**
   * A helper function to define multiple list items, supporting either an array of list items or a callback function receiving `helpers`.
   * For the callback signature, see the Helper Callback Pattern.
   */
  defineListItems: DefineListItems<T>;
  /**
   * A helper function to define a single list item, supporting either a list item object or a callback function receiving `helpers`.
   * For the callback signature, see the Helper Callback Pattern.
   */
  defineListItem: DefineListItem<T>;
  /**
   * The utility functions and builder helpers scoped to the structure tool config.
   */
  helpers: Helpers<T>;
}
