packages:
  - apps/*
  - configs/*
  - docs
  - packages/*

catalog:
  tsdown: ^0.22.3
  type-fest: ^5.7.0

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - prettier@3.9.1
